export const ClientInfo = {
  UNEXPECTED_EXCEPTION: 'UNEXPECTED_EXCEPTION',
  TECHNICAL_ISSUE: 'TECHNICAL_ISSUE',
  UNMET_CONSTRAINT: 'UNMET_CONSTRAINT',
  ENTITY_NOT_EXISTS: 'ENTITY_NOT_EXISTS',
  PERMISSION_DENIED:  'PERMISSION_DENIED'
};