DROP DATABASE IF EXISTS test_db;
CREATE DATABASE test_db;
USE test_db;

CREATE TABLE users (

  id INT UNSIGNED NOT NULL AUTO_INCREMENT,

  username VARCHAR(50) NOT NULL,
  email VARCHAR(50),
  pwdhash VARCHAR(132) NOT NULL,

  PRIMARY KEY(id),
  UNIQUE(username)

);