DROP DATABASE IF EXISTS test_db;
CREATE DATABASE test_db;
USE test_db;

CREATE TABLE users (

  id INT UNSIGNED NOT NULL AUTO_INCREMENT,

  username VARCHAR(50) NOT NULL,
  email VARCHAR(50),
  pwdhash VARCHAR(132) NOT NULL,

  PRIMARY KEY(id),
  UNIQUE(username)

);

CREATE TABLE roles (

  id INT UNSIGNED NOT NULL AUTO_INCREMENT,

  name VARCHAR(50) NOT NULL,

  PRIMARY KEY(id),
  UNIQUE(name)

);

CREATE TABLE user_roles (

  user_id INT UNSIGNED NOT NULL,
  role_id INT UNSIGNED NOT NULL,

  PRIMARY KEY(user_id, role_id),
  FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE ON UPDATE CASCADE

);